// <auto-generated />
namespace FastParts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CrearEncuestaServicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearEncuestaServicio));
        
        string IMigrationMetadata.Id
        {
            get { return "202603190507343_CrearEncuestaServicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
